### ISSUE TITLE
<br> tag on queryURL for some product on eLeclerc Drive

### ISSUE THREAD

**Issue by mickaelFR** [roiKosmic/DriveOff#2]
&lsaquo;br&rsaquo; tag is put on queryURL because of 2 lined titles. Example "Galettes riz Bjorg Complet - 130g" third product of the list on https://fd4-courses.leclercdrive.fr/magasin-997371-ELeclerc-Chez-Moi/recherche.aspx?TexteRecherche=galettes%20de%20riz

Problem from content_script.js
line201 : detail = elm.parent(".divWCRS310_HD").prevAll(".pWCRS310_Desc").find("a").html();

can be "fixed" with 
line 202 : detail = detail.replace('&lsaquo;br&rsaquo;',"");

or more globally with "html tag" deletion on filterTitle to avoid html tags on title search

**Comment by roiKosmic** [comment]
Fix in the last commit.
