### ISSUE TITLE
[1.0.1] Multiple "img.driveoff-openfood" because of multiple "dom mutation"

### ISSUE THREAD

**Issue by mickaelFR** [roiKosmic/DriveOff#6]
On Carrefour one "img.driveoff-openfood" (clicable icon of OFF) is added for each "dom mutation".

Perhaps the problem is located on  "carrefourfr.prototype.localMutationObserver=function(mutations,localThis)" on the file carrefourfr.js

**Comment by roiKosmic** [comment]
I think I have found the issue. I will fix it tomorrow.

**Comment by roiKosmic** [comment]
OK, i have fix the issue but not updated the repo yet as the fix raises some questions.
1/ To a good site integration, the off img cannot be appended easily. We need to decorate with ul:

<ul class='driveoff-openfood product-badges-list'><li class='product-badges-list__item'><img  src='"+this.DriveOffLocal.clickImgFile+"'></li>

So each drive needs to have its proper clickImgFileHTML.
